# permissions for end users to view microk8scontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microk8scontrolplane-viewer-role
rules:
- apiGroups:
  - cluster.cluster.x-k8s.io
  resources:
  - microk8scontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.cluster.x-k8s.io
  resources:
  - microk8scontrolplanes/status
  verbs:
  - get
