---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.cluster.x-k8s.io
  resources:
  - microk8scontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.cluster.x-k8s.io
  resources:
  - microk8scontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.cluster.x-k8s.io
  resources:
  - microk8scontrolplanes/status
  verbs:
  - get
  - patch
  - update
